- name: Make sure k3s config file dir exists
  file:
    path: "{{ k3s_config_file | dirname }}"
    state: directory

- name: Generate K3s Server config
  template:
    src: config.yaml.j2
    dest: "{{ k3s_config_file }}"

- name: Install K3s on worker nodes
  shell: >-
    ~/k3s_install.sh agent >> ~/k3s_install.log
  args:
    chdir: "~"
    creates: /var/lib/rancher/k3s/agent/kubelet.kubeconfig
